added pre and postscript feature feels like masterrelease

diff --git a/files/entrypoint b/files/entrypoint
--- a/files/entrypoint
+++ b/files/entrypoint
@@ -2,7 +2,7 @@
 set -Eeo pipefail
 
 function log() {
-    echo "[$(date)][$0] $*" >&2
+    echo "[$(date)][$0]: $*" >&2
 }
 
 # shellcheck disable=2154
@@ -17,7 +17,7 @@ userConfFinalPath="/var/run/sftp/users.conf"
 
 if [[ -z "$acipersistPath" ]]; then
     acipersistPath="/home/acipersist"
-    log "found $acipersistPath"
+    log "using $acipersistPath as acipersistPath"
 fi
 
 if [[ -f "$acipersistPath"/users.conf ]]; then
@@ -31,6 +31,19 @@ if [[ -z "$1" || "$1" =~ $reArgsMaybe ]]; then
     startSshd=true
 else
     startSshd=false
+fi
+
+# Source custom scripts to run first
+if [[ -d "$acipersistPath"/prescripts ]] ; then
+    for f in "$acipersistPath"/prescripts/*; do
+        if [[ -x "$f" ]]; then
+            log "Running $f ..."
+            $f
+        else
+            log "Could not run $f, because it's missing execute permission (+x)."
+        fi
+    done
+    unset f
 fi
 
 # Backward compatibility with legacy config path
@@ -88,45 +101,27 @@ if [[ ! -f "$userConfFinalPath" ]]; then
     else
         log "couldn't find $aciHostkeysPath"
     fi
-
     if [ ! -e "$aciHostkeysPath" ]; then
         mkdir -p "$aciHostkeysPath"
         log "created $aciHostkeysPath"
     fi
-
-    if [ ! -f /etc/ssh/ssh_host_ed25519_key ] ; then
+    if [ ! -f "/etc/ssh/ssh_host_ed25519_key" ] ; then
         log "couldnt find /etc/ssh/ssh_host_ed25519_key"
-        ssh-keygen -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -N '' -E md5
+        ssh-keygen -t ed25519 -E md5 -f /etc/ssh/ssh_host_ed25519_key -N ''
         if [ ! -e "$aciHostkeysPath/ssh_host_ed25519_key" ]; then
-            cp /etc/ssh/ssh_host_ed25519_key "$aciHostkeysPath"/ssh_host_ed25519_key
+            cat /etc/ssh/ssh_host_ed25519_key > "$aciHostkeysPath"/ssh_host_ed25519_key
+            log "added ed25519 hostkey to $aciHostkeysPath"
         fi
     fi
-
-    if [ ! -f /etc/ssh/ssh_host_rsa_key ]; then
+    if [ ! -f "/etc/ssh/ssh_host_rsa_key" ]; then
         log "couldnt find /etc/ssh/ssh_host_rsa_key"
-        ssh-keygen -t rsa -b 2048 -f /etc/ssh/ssh_host_rsa_key -N '' -E md5
+        ssh-keygen -t rsa -E md5 -b 2048 -f /etc/ssh/ssh_host_rsa_key -N ''
         if [ ! -e "$aciHostkeysPath/ssh_host_rsa_key" ]; then
             cat /etc/ssh/ssh_host_rsa_key > "$aciHostkeysPath"/ssh_host_rsa_key
             log "added rsa hostkey to $aciHostkeysPath"
         fi
     fi
-
 fi
-
-
-# Source custom scripts, if any
-if [[ -d "$acipersistPath"/scripts ]] ; then
-    for f in "$acipersistPath"/scripts/*; do
-        if [[ -x "$f" ]]; then
-            log "Running $f ..."
-            $f
-        else
-            log "Could not run $f, because it's missing execute permission (+x)."
-        fi
-    done
-    unset f
-fi
-
 
 # copy sshd_config from /acipersist if exists, if doesnt exist copy it from /etc/ssh to /acipersist
 aciSshdConfig="$acipersistPath/sshd_config"
@@ -145,10 +140,30 @@ elif [[ /etc/ssh/sshd_config -ot "$aciSshdConfig" ]] ; then
 fi
 
 # Generate public keys for this container
-for f in /etc/ssh/*_key; do
-    ssh-keygen -y -f "$f" > "$f".pub
-    log "generated $f.pub"
-done
+if [ -e "/etc/ssh/ssh_host_*_key.pub" ] ; then
+    for f in /etc/ssh/ssh_host_*_key.pub; do
+        log "$(ssh-keygen -l -E md5 -f $f)"
+    done
+else
+    log "generating SSH Host Public Keys"
+    for f in /etc/ssh/ssh_host_*_key; do
+        ssh-keygen -y -E md5 -f "$f" > "$f".pub
+        log "$(ssh-keygen -l -E md5 -f $f)"
+    done
+fi
+
+# Source custom scripts, if any
+if [[ -d "$acipersistPath"/scripts ]] ; then
+    for f in "$acipersistPath"/scripts/*; do
+        if [[ -x "$f" ]]; then
+            log "Running $f ..."
+            $f
+        else
+            log "Could not run $f, because it's missing execute permission (+x)."
+        fi
+    done
+    unset f
+fi
 
 if $startSshd; then
     log "Executing sshd"
