last minute updates

diff --git a/files/entrypoint b/files/entrypoint
--- a/files/entrypoint
+++ b/files/entrypoint
@@ -9,22 +9,15 @@ reArgSkip='^([[:blank:]]*#.*|[[:blank:]]*)$' # comment or empty line
 
 # Paths
 userConfPath="/etc/sftp/users.conf"
-userConfPathLegacy="/mnt/acipersist/sftp/users.conf"
+userConfPathLegacy="/etc/sftp-users.conf"
 userConfFinalPath="/var/run/sftp/users.conf"
 acipersistPath="/mnt/acipersist"
 acipersistRepo="/mnt/sftp-aci"
 
 function log() {
-    echo "[ $(date) entrypoint ] $*" >&2
+    echo "[$0] [$(date)] $*" >&2
 }
 
-if [[ -e "$acipersistPath/sftp/users.conf" ]]; then
-    # userConfPath="$($acipersistPath/sftp/users.conf)"
-    log "changing userConfPath to $acipersistPath/sftp/users.conf"
-    userConfPath="$acipersistPath/sftp/users.conf"
-else
-    log "couldnt find $acipersistPath/sftp/users.conf"
-fi
 
 # Allow running other programs, e.g. bash
 if [[ -z "$1" || "$1" =~ $reArgsMaybe ]]; then
@@ -45,9 +38,8 @@ if [[ ! -e "$acipersistPath" ]]; then
         log "repo not found at $acipersistRepo"
         # Todo - clone git repo???
     fi
-else
-    log "using $acipersistPath as acipersistPath"
 fi
+
 
 
 # Backward compatibility with legacy config path
@@ -60,9 +52,12 @@ fi
 if [[ ! -f "$userConfFinalPath" ]]; then
     mkdir -p "$(dirname $userConfFinalPath)"
 
-    if [[ -f "$userConfPath" ]]; then
+    aciuserconf=$acipersistPath/sftp/users.conf
+    echo "copied $aciuserconf to $userConfPath"
+
+    if [[ -f "$aciuserconf" ]]; then
         # Append mounted config to final config
-        grep -v -E "$reArgSkip" < "$userConfPath" > "$userConfFinalPath"
+        grep -v -E "$reArgSkip" < "$aciuserconf" > "$userConfFinalPath"
     fi
 
     if $startSshd; then
@@ -103,10 +98,8 @@ if [[ ! -f "$userConfFinalPath" ]]; then
             cp "$ed25519_hostkey" /etc/ssh/ssh_host_ed25519_key
             chmod 600 /etc/ssh/ssh_host_ed25519_key
             log "copied $ed25519_hostkey to /etc/ssh"
-            if [[ ! -f "/etc/ssh/ssh_host_ed25519_key.pub" ]]; then
-                log "generating missing public key for $ed25519_hostkey"
-                ssh-keygen -y -f /etc/ssh/ssh_host_ed25519_key > /etc/ssh/ssh_host_ed25519_key.pub
-            fi
+            log "generating missing public key for $ed25519_hostkey"
+            ssh-keygen -y -f /etc/ssh/ssh_host_ed25519_key > /etc/ssh/ssh_host_ed25519_key.pub
         else
             log "couldnt find $ed25519_hostkey, generating new key"
             ssh-keygen -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -N '' -E md5
@@ -131,7 +124,7 @@ if [[ ! -f "$userConfFinalPath" ]]; then
             log "couldnt find $rsa_hostkey, generating new key"
             ssh-keygen -t rsa -b 4096 -f /etc/ssh/ssh_host_rsa_key -N '' -E md5
             if [[ -e "$acipersistPath" ]]; then
-                cp /etc/ssh/ssh_host_rsa_key "$acipersistPath/hostkeys/" && log "copied rsa hostkey to $rsa_hostkey"
+                cp "$acipersistPath/hostkeys/" && log "copied rsa hostkey to $rsa_hostkey"
             fi
         fi
     fi
@@ -142,7 +135,7 @@ fi
 
 # Source custom scripts, if any
 if [[ -d $acipersistPath/scripts ]]; then
-    for f in "$acipersistPath/scripts/*.sh" ; do
+    for f in $acipersistPath/scripts/*.sh ; do
         if [[ -x "$f" ]]; then
             log "Running $f ..."
             $f
