updated readmes,  Dockerfile, entrypoint,... added date to output better filehandling updated ignorefiles change location of users.conf

diff --git a/files/entrypoint b/files/entrypoint
--- a/files/entrypoint
+++ b/files/entrypoint
@@ -12,10 +12,17 @@ userConfPath="/etc/sftp/users.conf"
 userConfPathLegacy="/etc/sftp-users.conf"
 userConfFinalPath="/var/run/sftp/users.conf"
 acipersistPath="/mnt/acipersist"
+acipersistRepo="/mnt/sftp-aci"
 
 function log() {
-    echo "[$0] $*" >&2
+    echo "[$(date) entrypoint] $*" >&2
 }
+
+if [ -e "$acipersistPath/sftp/users.conf" ]; then
+    # userConfPath="$($acipersistPath/sftp/users.conf)"
+    ln -s "$acipersistPath/sftp/users.conf" "$userConfPath"
+    log "linked acipersist users.conf to $userConfPath"
+fi
 
 # Allow running other programs, e.g. bash
 if [[ -z "$1" || "$1" =~ $reArgsMaybe ]]; then
@@ -23,6 +30,23 @@ if [[ -z "$1" || "$1" =~ $reArgsMaybe ]]; then
 else
     startSshd=false
 fi
+
+# link repositorys AciPersist folder if repo is cloned into /mnt/sftp-aci-repo
+if [ ! -e "$acipersistPath" ]; then
+    log "missing $acipersistPath, trying to link it from $acipersistRepo"
+    if [ -e "$acipersistRepo/AciPersist" ]; then
+        # acipersistPath="$acipersistRepo/AciPersist"
+        # log "changing acipersistPath to $acipersistPath"
+        ln -s "$acipersistRepo/AciPersist" "$acipersistPath"
+        log "linked $acipersistRepo/AciPersist to $acipersistPath"
+    else
+        log "repo not found at $acipersistRepo"
+        # Todo - clone git repo???
+    fi
+else
+    log "using $acipersistPath as acipersistPath"
+fi
+
 
 # Backward compatibility with legacy config path
 if [ ! -f "$userConfPath" ] && [ -f "$userConfPathLegacy" ]; then
@@ -65,39 +89,42 @@ if [ ! -f "$userConfFinalPath" ]; then
         exit 3
     fi
 
-    # copy keys from acipersist unique ssh keys for this container, if needed
-    if [ -f "$acipersistPath/hostkeys/ssh_host_*_key" ]; then
-        echo "Copy over hostkeys from acipersist"
-        cp "$acipersistPath/hostkeys/ssh_host_ed25519_key" /etc/ssh/ssh_host_ed25519_key
-        chmod 600 /etc/ssh/ssh_host_ed25519_key
-    fi
-
     # Generate unique ssh keys for this container, if needed
+    ed25519_hostkey="$acipersistPath/hostkeys/ssh_host_ed25519_key"
+    rsa_hostkey="$acipersistPath/hostkeys/ssh_host_rsa_key"
     if [ ! -f /etc/ssh/ssh_host_ed25519_key ]; then
+        if [ -f "$ed25519_hostkey" ]; then
+            log "found $ed25519_hostkey"
+            cp "$ed25519_hostkey" /etc/ssh/ssh_host_ed25519_key
+            chmod 600 /etc/ssh/ssh_host_ed25519_key
+        else
+        log "couldnt find $ed25519_hostkey"
         ssh-keygen -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -N ''
-        # Todo: add else generate pub
+        log "copy key to $ed25519_hostkey"
+        cp /etc/ssh/ssh_host_ed25519_key "$ed25519_hostkey"
+        fi
     fi
-    
-    if [ -f "$acipersistPath/hostkeys/ssh_host_rsa_key" ]; then
-        echo "Copy over hostkeys from acipersist"
-        cp "$acipersistPath/hostkeys/ssh_host_rsa_key" /etc/ssh/ssh_host_rsa_key
-        chmod 600 /etc/ssh/ssh_host_rsa_key
-    fi
-
     if [ ! -f /etc/ssh/ssh_host_rsa_key ]; then
+        if [ -f "$rsa_hostkey" ]; then
+            log "found $rsa_hostkey"
+            cp "$rsa_hostkey" /etc/ssh/ssh_host_rsa_key
+            chmod 600 /etc/ssh/ssh_host_rsa_key
+        else
+        log "couldnt find $rsa_hostkey"
         ssh-keygen -t rsa -b 4096 -f /etc/ssh/ssh_host_rsa_key -N ''
+        log "copy rsa hostkey to $rsa_hostkey"
+        # cp /etc/ssh/ssh_host_rsa_key "$acipersistPath/hostkeys/"
         # Todo: add else generate pub
+        fi
     fi
 fi
 
 # Source custom scripts, if any
 if [ -d $acipersistPath/scripts ]; then
-    for f in $acipersistPath/scripts/*; do
+    for f in "$acipersistPath"/scripts/*.sh; do
         if [ -x "$f" ]; then
             log "Running $f ..."
             $f
-        elif [ -f "$f" ]; then
-            log "ignoring readme.md"
         else
             log "Could not run $f, because it's missing execute permission (+x)."
         fi
